# Generated by Django 2.2.8 on 2019-12-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawFromApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('tags_str', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_permanent_id', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('tokens', models.TextField(blank=True, null=True)),
                ('smilar_articles', models.TextField(blank=True, null=True)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
                ('smilar_articles_vec60', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_from_api',
                'managed': False,
            },
        ),
    ]
