# Generated by Django 2.2.8 on 2020-01-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rawfromapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('vector', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_vector',
                'managed': False,
            },
        ),
    ]
