# Generated by Django 2.2.8 on 2020-01-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlevector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSimilarArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(blank=True, max_length=50, null=True)),
                ('similar_article_id', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_similar_articles',
                'managed': False,
            },
        ),
    ]
